/* Generated By:JavaCC: Do not edit this line. sqlparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface sqlparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 4;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int DROP_TABLE = 10;
  /** RegularExpression Id. */
  int INSERT_INTO = 11;
  /** RegularExpression Id. */
  int DESC = 12;
  /** RegularExpression Id. */
  int DELETE_FROM = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int SHOW_TABLES = 15;
  /** RegularExpression Id. */
  int NOT_NULL = 16;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 17;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 18;
  /** RegularExpression Id. */
  int REFERENCES = 19;
  /** RegularExpression Id. */
  int VALUES = 20;
  /** RegularExpression Id. */
  int AS = 21;
  /** RegularExpression Id. */
  int FROM = 22;
  /** RegularExpression Id. */
  int WHERE = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int NOT = 26;
  /** RegularExpression Id. */
  int IS = 27;
  /** RegularExpression Id. */
  int STAR = 28;
  /** RegularExpression Id. */
  int NULL = 29;
  /** RegularExpression Id. */
  int CREATE = 30;
  /** RegularExpression Id. */
  int TABLE = 31;
  /** RegularExpression Id. */
  int DROP = 32;
  /** RegularExpression Id. */
  int SHOW = 33;
  /** RegularExpression Id. */
  int TABLES = 34;
  /** RegularExpression Id. */
  int INSERT = 35;
  /** RegularExpression Id. */
  int INTO = 36;
  /** RegularExpression Id. */
  int DELETE = 37;
  /** RegularExpression Id. */
  int PRIMARY = 38;
  /** RegularExpression Id. */
  int FOREIGN = 39;
  /** RegularExpression Id. */
  int KEY = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int LEFT_PAREN = 42;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 43;
  /** RegularExpression Id. */
  int COMMA = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;
  /** RegularExpression Id. */
  int UNDERSCORE = 46;
  /** RegularExpression Id. */
  int SIGN = 47;
  /** RegularExpression Id. */
  int PERIOD = 48;
  /** RegularExpression Id. */
  int DIGIT = 49;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 50;
  /** RegularExpression Id. */
  int ALPHABET = 51;
  /** RegularExpression Id. */
  int COMP_OP = 52;
  /** RegularExpression Id. */
  int INT_VALUE = 53;
  /** RegularExpression Id. */
  int NNNN = 54;
  /** RegularExpression Id. */
  int NN = 55;
  /** RegularExpression Id. */
  int DATE_VALUE = 56;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARS = 57;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARS = 58;
  /** RegularExpression Id. */
  int CHAR_STRING = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"drop table\"",
    "\"insert into\"",
    "\"desc\"",
    "\"delete from\"",
    "\"select\"",
    "\"show tables\"",
    "\"not null\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"values\"",
    "\"as\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"is\"",
    "\"*\"",
    "\"null\"",
    "\"create\"",
    "\"table\"",
    "\"drop\"",
    "\"show\"",
    "\"tables\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"primary\"",
    "\"foreign\"",
    "\"key\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"\\\'\"",
    "\"_\"",
    "<SIGN>",
    "\".\"",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<COMP_OP>",
    "<INT_VALUE>",
    "<NNNN>",
    "<NN>",
    "<DATE_VALUE>",
    "<NON_QUOTE_CHARS>",
    "<NON_QUOTE_SPECIAL_CHARS>",
    "<CHAR_STRING>",
  };

}
